export const en = {
  LANGUAGE: 'language',
  TITLE: 'title',
  SUMMARY: 'summary',
  ATTRIBUTE: 'attribute',
  ARRAY: 'array',
  OBJECT: 'object',
  GOAL: 'goal',
  REM: 'rem',
  COMMENT: 'comment',
  RULE: 'rule',
  IF: 'if',
  AND: 'and',
  OR: 'or',
  THEN: 'then',
  ELSEIF: 'else if',
  ELSE: 'else',
  PROMPT: 'prompt',
  QUESTION: 'question',
  MENU: 'menu',
  DIGIT: 'DIGIT',
  TEXT: 'text',
  CF: '%',
  LOAD: 'load',
  IS: 'is',
  IN: 'in',
  INCLUDE: 'include',
  EXCLUDE: 'exclude',
  TRUE: 'true',
  FALSE: 'false',
  MIN: 'min',
  MAX: 'max',
  // FOLD_SETTING:			fold.en,
  // PROMPT_SETTING:		prompt.en
}

export const fr = {
  LANGUAGE: 'langue',
  TITLE: 'titre',
  SUMMARY: 'résumé',
  ATTRIBUTE: 'attribut',
  ARRAY: 'tableau',
  OOBJECT: 'objet',
  GOAL: 'objetif',
  REM: 'rem',
  COMMENT: 'commentaire',
  RULE: 'règle',
  IF: 'si',
  AND: 'et',
  OR: 'ou',
  THEN: 'puis',
  ELSEIF: 'elseif',
  ELSE: 'autre',
  PROMPT: 'contribution',
  QUESTION: 'question',
  MENU: 'menu',
  DIGIT: 'digit',
  TEXT: 'texte',
  CF: '%',
  LOAD: 'charge',
  IS: 'est',
  IN: 'dans',
  INCLUDE: 'comprendre',
  EXCLUDE: 'exclure',
  TRUE: 'vrai',
  FALSE: 'faux',
  MIN: 'min',
  MAX: 'max',
  // FOLD_SETTING:			fold.fr,
  // PROMPT_SETTING:		prompt.fr
}

export default {
  en,
  fr
}